#!/usr/bin/env node
// Generated by CoffeeScript 1.6.3
var HOME, config, exitWithError, fileExists, fs, i3Path, mkConfig, pathUtil, program, sh, theme, themesAvailable, themesDir, tmpConfigPath, tmpdir, validation, yaml, _ref,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

fs = require('fs');

sh = require('shelljs');

program = require('commander');

yaml = require('js-yaml');

pathUtil = require('path');

mkConfig = require('./index').mkConfig;

sh.config.silent = true;

program.version('0.0.1').usage('<theme> [options]').option('-c, --config <file>', 'The config file the theme should be applied to. Defaults to the default i3 location.').option('-o, --output <file>', 'Applies the theme, attempts to validate the result, and writes it to <file>. Prints to STDOUT if no output file is given.').parse(process.argv);

fileExists = function(path) {
  return (path != null) && sh.test('-f', path);
};

exitWithError = function(msg) {
  program.outputHelp();
  process.stderr.write("Error: " + msg);
  return process.exit(1);
};

themesDir = pathUtil.resolve(__dirname, '../themes');

themesAvailable = sh.ls(themesDir);

if (!(fileExists(program.args[0]) || (_ref = program.args[0], __indexOf.call(themesAvailable, _ref) >= 0))) {
  exitWithError("Theme or file not found: " + program.args[0]);
}

theme = (function() {
  var _ref1;
  switch (false) {
    case !program.args[0].match(/\.json$/):
      return JSON.parse(sh.cat(program.args[0]));
    case !program.args[0].match(/\.yaml$/):
      return yaml.safeLoad(sh.cat(program.args[0]));
    case _ref1 = program.args[0], __indexOf.call(themesAvailable, _ref1) < 0:
      return yaml.safeLoad(sh.cat(pathUtil.join(themesDir, program.args[0])));
    default:
      return exitWithError("Theme must be a valid json or yaml file or a builtin theme");
  }
})();

if ((program.config != null) && !fileExists(program.config)) {
  exitWithError("Config file not found: " + program.config);
}

HOME = process.env.HOME;

config = (function() {
  switch (false) {
    case !program.config:
      return sh.cat(program.config);
    case !(HOME && fileExists("" + HOME + "/.i3/config")):
      return sh.cat("" + HOME + "/.i3/config");
    case !(HOME && fileExists("" + HOME + "/.config/i3/config")):
      return sh.cat("" + HOME + "/.config/i3/config");
    default:
      return exitWithError("Could not find a valid i3 config file");
  }
})();

config = mkConfig(theme, config);

if (!program.output) {
  sh.echo(config);
  process.exit(0);
}

i3Path = sh.which('i3');

tmpdir = sh.tempdir();

if (i3Path && tmpdir) {
  tmpConfigPath = pathUtil.join(tmpdir, 'i3-style-config');
  fs.writeFileSync(tmpConfigPath, config);
  if (fileExists(tmpConfigPath)) {
    validation = sh.exec("" + i3Path + " -c " + tmpConfigPath + " -C");
    sh.rm(tmpConfigPath);
    if (validation.output.indexOf('ERROR:') > 0 || validation.code > 0) {
      exitWithError("Could not validate output configuration.\n\n" + validation.output);
    }
  }
}

fs.writeFile(program.output, config, function(err) {
  if (err) {
    return exitWithError("Could not write to file: " + program.output + "\n\n" + err);
  }
});
